sonar.projectKey=Cristiano2132_model_track_cr
sonar.projectName=model-track-cr
sonar.organization=cristiano2132

sonar.sources=src/model_track
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8