sonar.projectKey=Cristiano2132_model-track-cr
sonar.projectName=model-track-cr
sonar.organization=cristiano2132-1

sonar.sources=src
sonar.tests=tests

sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml