

sonar.projectKey=Cristiano2132_model-track-cr
sonar.projectName=model-track-cr
sonar.organization=cristiano2132-1
sonar.python.version=3.10, 3.11, 3.12, 3.13

# Caminhos para código e testes
sonar.sources=src
sonar.tests=tests
sonar.python.xunit.reportPath=pytest-report.xml
sonar.python.coverage.reportPaths=coverage.xml

# Excluir ficheiros que não precisam de análise
sonar.exclusions=tests/**, .venv/**, build/**
