name: SonarCloud

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Importante para o Sonar entender o histórico de blame

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        # Ajustado para o seu pyproject.toml
        run: poetry install --no-interaction --with dev

      - name: Run tests with coverage
        # Gerando o XML que o sonar-project.properties vai ler
        run: |
          poetry run pytest --cov=src --cov-report=xml:coverage.xml --cov-fail-under=0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}